version: '3.3'
services:
  tomcat:
    depends_on:
      - mongo
    image: guilhemsempere/gigwa:2.3-RELEASE
    ports:
      - "${PORT}:8080" # You may amend the external port only (left hand side). By default, webapp URL will be http://host.ip:8080/gigwa
    restart: always
    environment:
      MONGO_IP: mongo
      MONGO_PORT: 27017 # Must match mongo container port
      MONGO_INITDB_ROOT_USERNAME: yourMongoRootUser
      MONGO_INITDB_ROOT_PASSWORD: yourMongoRootPassword
      HOST_LOCALE: "${LANG}"
    healthcheck:
      test: wget -q --spider http://localhost:8080/gigwa || exit 1
    volumes:
      - type: volume
        source: gigwa
        target: /usr/local/tomcat/config

  mongo:
    image: mongo:4.2.12
    restart: always
    command: --profile 0 --slowms 60000 --storageEngine wiredTiger --wiredTigerCollectionBlockCompressor=zlib --directoryperdb --quiet
    expose:
      - 27017 # default mongodb port
    environment:
      MONGO_INITDB_ROOT_USERNAME: yourMongoRootUser
      MONGO_INITDB_ROOT_PASSWORD: yourMongoRootPassword
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
    volumes:
      - type: volume
        source: mongo
        target: /data/db

volumes:
  gigwa:
  mongo:
